
_DISTRIB_NAME := $(shell sed -n '/^.*distribution=\([^,]*\),.*/s//\1/p' /etc/product.id)
DISTRIB_NAME = "$(_DISTRIB_NAME)"
DISTRIB_VERSION = $(shell sed -n '/^.*version=\([^,]*\),.*/s//\1/p' /etc/product.id)
DISTRIB_TYPE = $(shell sed -n '/^.*type=\([^,]*\),.*/s//\1/p' /etc/product.id)
DISTRIB_DESCR = "$(_DISTRIB_NAME) release $(DISTRIB_VERSION)"


# not config, but useful everywhere :)
ARCH := $(patsubst i%86,i386,$(shell uname -m))
ARCH := $(ARCH:sparc%=sparc)
ARCH := $(ARCH:arm%=arm)

PKG_ARCH := $(ARCH:i386=i586)

ifeq (x86_64, $(ARCH))
LIB = lib64
else
LIB = lib
endif
